ROLE_SALES_SUPERVISOR = "Sales Supervisor"
ROLE_WAREHOUSE_MANAGER = "Warehouse Manager"
ROLE_STOCK_MANAGER = "Stock Manager"
ROLE_ADMINISTRATOR = "Administrator"

TRANSFER_ROLE_PRIORITY = (
    ROLE_ADMINISTRATOR,
    ROLE_STOCK_MANAGER,
    ROLE_WAREHOUSE_MANAGER,
    ROLE_SALES_SUPERVISOR,
)

TYPE_SEND_STOCK = "Send Stock"
TYPE_RECEIVE_STOCK = "Receive Stock"
TYPE_TRANSFER_BETWEEN = "Transfer Between"

RECEIVING_NORMAL = "Normal Receiving"
RECEIVING_BARCODE = "Manual / Barcode Receiving"

WAREHOUSE_TRANSIT_TYPE = "Transit"
TRANSIT_PREFIX = "T-"
